spring.application.name=account

server.port=8000
server.address=0.0.0.0

spring.jpa.open-in-view=false

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.config-url=../api-docs/swagger-config
springdoc.swagger-ui.url=../api-docs
springdoc.swagger-ui.disable-swagger-default-url=true