spring.application.name=client

server.port=8001
server.address=0.0.0.0

spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.jackson.time-zone=America/Guayaquil

logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR

account.service.url=http://localhost:8000

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.config-url=../api-docs/swagger-config
springdoc.swagger-ui.url=../api-docs
springdoc.swagger-ui.disable-swagger-default-url=true